### ISSUE TITLE
Убрать из эндпоинта get_all_organizations лишние данные; переименовать в organizations

### ISSUE THREAD

**Issue by shinnik** [alekseik1/tt-ridesharing-backend#12]
Как бы хотел это видеть фронт в соответствии с макетами:

GET organizations/
Без параметров
response: {
    organizations: [
        {
              id: string;
              name: string;
              address: string;  
         }
    ]
}

По этому эндпоинту пользователь должен получать **только свои организации**

**Comment by alekseik1** [comment]
@shinnik уже есть `GET /organization` в #20. Чтобы не было путаницы, эндпоинт будет `GET /user/organizations`

**Comment by shinnik** [comment]
@alekseik1 Окей!

**Comment by alekseik1** [comment]
Сделано в 84cb5e3e5a08079114bff7237f3f56d823e6e734
