### ISSUE TITLE
GET **/rides/active**

### ISSUE THREAD

**Issue by alekseik1** [alekseik1/tt-ridesharing-backend#23]
*query-параметры отсутствуют*

Тело ответа:
`rides: Array{
RideId: string;
amountOfFreePlaces: string; // кол-во свободных мест
time: string; //ISO время отправления
Driver: {DriverId: string; firstName: string; lastName: string; avatarSrc: string; rating: string;};
Cost: string;
Car: {model: string; licensePlateNumber: string; color: string};
DestinationAddress: string;
DriverAnswer: "ACCEPT" | "DECLINE" | "WAITING" | "CANCELLED";
DeclineReason: string;
DriverPhoneNumber: string
}`

**Comment by alekseik1** [comment]
@Kyzyl-ool это типа мои активные поездки, да?

**Comment by alekseik1** [comment]
Сделано в 4d17dfc030dea87183184f36b6df42f968b33f4d

**Comment by Kyzyl-ool** [comment]
Тут надо добавить поля с адресом организации, откуда ты отправляешься

**Comment by alekseik1** [comment]
@Kyzyl-ool будет так
```json
[
  {
    "car": {
      "color": "greed",
      "id": 5,
      "model": "Renault Clio",
      "owner": 55,
      "registryNumber": "К982ХР779"
    },
    "declineReason": "",
    "freeSeats": 3,
    "host": {
      "firstName": "Eli",
      "id": 55,
      "lastName": "Spears",
      "phoneNumber": "+79500000000",
      "photoUrl": "https://ridesharing-photos.com/photo1.jpg",
      "rating": 0.0
    },
    "hostAnswer": "ACCEPTED",
    "id": 5,
    "price": 350.0,
    "startOrganization": {
      "address": "Россия, Московская область, городской округ Подольск",
      "id": 2,
      "name": "Pasta salad restaurant"
    },
    "stopAddress": "Россия, Московская область, городской округ Подольск",
    "submitDatetime": "2020-04-02T12:17:19.088954"
  }
]
```
