### ISSUE TITLE
GET **/user**

### ISSUE THREAD

**Issue by alekseik1** [alekseik1/tt-ridesharing-backend#30]
Query-параметры:
`UserId: string;`

Тело ответа:
`
FirstName: string;
LastName: string;
Rating: string;
About: string;
avatarSrc: string;
`

**Comment by alekseik1** [comment]
@Kyzyl-ool @shinnik добавлю фичу: если не передать `id` в запросе, то будет возвращать текущего пользователя. Причина: во время тестов я не нашел ни одного способа узнать, кто я такой

**Comment by Kyzyl-ool** [comment]
Леша, а где поле "about"?

**Comment by Kyzyl-ool** [comment]
Или давай данные по профилю пользователя будешь выдавать в GET **/profile**
