### ISSUE TITLE
Фотки в S3 хранилище

### ISSUE THREAD

**Issue by alekseik1** [alekseik1/tt-ridesharing-backend#49]
Пора!

Кому это надо:
- [ ] Аватарки пользователей
- [ ] Аватарки организаций

**Comment by alekseik1** [comment]
@Kyzyl-ool @shinnik дайте знать, как сверстаете на фронте. На всякий случай, скопирую сюда сообщения с телеги

> Aleksei Kozharin, [4 Apr 2020, 12:34:27]:
> короче, история такая. Тру-пацаны советуют заливать картинки в S3 на стороне фронта, ибо загрузка может занимать много времени и если ее делать с бека, то может отвалиться по таймауту соединение фронт-бек.
> Но credentials для S3 нельзя раздавать фронту, поэтому работа разбивается на такой пайп:
> 1) Фронт запрашивает подписанный урл для загрузки конкретно этого файла
> 2) Бек отдает подписанный урл и еще какую-то инфу (типа ключа и каких-то строк авторизации, я еще не очень разобрался сам), которую надо будет скормить S3 при заливе картинки
> 3) Фронт отправляет запрос непосредственно на хранилище S3, куда в `form-data` передает файл и эти самые данные авторизации, полученные с бека в п.2
> 4) Картинка заливается с фронта, по окончании фронт получает урл на загруженную картинку.
> 
> Урл на полученную картинку будет только на фронте. Поэтому я попрошу вас отправить его на бек (наверно, придется принимать с фронта поле `photoUrl` на эндпоинте регистрации)
> 
> инфу брал отсюда
> https://devcenter.heroku.com/articles/s3-upload-python

**Comment by shinnik** [comment]
@alekseik1 пушу эту задачу

**Comment by shinnik** [comment]
Нам она нужна

**Comment by alekseik1** [comment]
Сделано и залито на staging и master
