### ISSUE TITLE
Эндпоинт на поездки, которые ты захостил

### ISSUE THREAD

**Issue by alekseik1** [alekseik1/tt-ridesharing-backend#52]

**Comment by alekseik1** [comment]
Сделано в f64af44d472616fba5464b267669acd7fe5c9268

**Comment by Kyzyl-ool** [comment]
Какой формат получения данных?

`
[
  {
    "car": {
      "color": "greed",
      "id": 1,
      "model": "Peel Trident",
      "owner": 51,
      "registryNumber": "К104ХР779"
    },
    "declineReason": null,
    "freeSeats": 1,
    "host": {
      "firstName": "Glen",
      "id": 51,
      "lastName": "Rutledge",
      "phoneNumber": "+79500000000",
      "photoUrl": "https://ridesharing-photos.com/photo1.jpg",
      "rating": 0.0
    },
    "hostAnswer": null,
    "id": 1,
    "price": 350.0,
    "stopAddress": "Россия, Москва, поселение Первомайское, коттеджный посёлок Подмосковные Вечера, 3-й Рогозининский переулок, 30",
    "submitDatetime": "2020-04-02T12:17:19.088954"
  }
]
`


Такой?

**Comment by alekseik1** [comment]
> Какой формат получения данных?
> 
> 
> 
> `
> 
> [
> 
>   {
> 
>     "car": {
> 
>       "color": "greed",
> 
>       "id": 1,
> 
>       "model": "Peel Trident",
> 
>       "owner": 51,
> 
>       "registryNumber": "К104ХР779"
> 
>     },
> 
>     "declineReason": null,
> 
>     "freeSeats": 1,
> 
>     "host": {
> 
>       "firstName": "Glen",
> 
>       "id": 51,
> 
>       "lastName": "Rutledge",
> 
>       "phoneNumber": "+79500000000",
> 
>       "photoUrl": "https://ridesharing-photos.com/photo1.jpg",
> 
>       "rating": 0.0
> 
>     },
> 
>     "hostAnswer": null,
> 
>     "id": 1,
> 
>     "price": 350.0,
> 
>     "stopAddress": "Россия, Москва, поселение Первомайское, коттеджный посёлок Подмосковные Вечера, 3-й Рогозининский переулок, 30",
> 
>     "submitDatetime": "2020-04-02T12:17:19.088954"
> 
>   }
> 
> ]
> 
> `
> 
> 
> 
> 
> 
> Такой?

Ага, только еще (как бонус) приходит инфа о стартовой организации (имя, адрес и id)
