### ISSUE TITLE
Тут надо добавить поля с адресом организации, откуда ты отправляешься

### ISSUE THREAD

**Issue by Kyzyl-ool** [alekseik1/tt-ridesharing-backend#53]
Тут надо добавить поля с адресом организации, откуда ты отправляешься

_Originally posted by @Kyzyl-ool in https://github.com/alekseik1/tt-ridesharing-backend/issues/23#issuecomment-608361495_

**Comment by Kyzyl-ool** [comment]
Либо сделать эндпоинт, где можно узнать информацию о поездке по rideId

**Comment by alekseik1** [comment]
См. [здесь](https://github.com/alekseik1/tt-ridesharing-backend/issues/23#issuecomment-608374356)

**Comment by alekseik1** [comment]
Сделано в ce83e601828fb614484870289b9ba9e04d8be6fa
