### ISSUE TITLE
GET **/verify**

### ISSUE THREAD

**Issue by Kyzyl-ool** [alekseik1/tt-ridesharing-backend#56]
*query-запросы отсутствуют. В запросе могут быть куки*

Если куки есть и они валидны – вернуть 200 OK.
Если куки есть, но они невалидны – вернуть 200 INVALID COOKIE
Если куки отсутствуют – вернуть 200 NO COOKIE

**Comment by alekseik1** [comment]
Решил исправлением status code для login на 200 при `"already logged-in"`
