### ISSUE TITLE
/rides/active присылает неконсистентную поездку

### ISSUE THREAD

**Issue by shinnik** [alekseik1/tt-ridesharing-backend#58]
Обычно интерфейс выглядит так:
`export interface IRide {
  car: ICar;
  freeSeats: number;
  host: IDriver;
  id: number;
  passengers: IPassenger[];
  price: number;
  startOrganizationAddress: string;
  stopAddress: string;
  submitDatetime: string;
  hostAnswer: IHostAnswer;
}`
А приходит вместо startOrganizationAddress объект startOrganization, где есть адрес внутри, но все же компонент это ломает

Хотелось бы, чтобы приходил startOrganizationAddress как и всегда

**Comment by shinnik** [comment]
Кроме того, не приходят пассажиры :(

**Comment by alekseik1** [comment]
@shinnik Будет `startOrganzationAddress` в первом уровне вложенности (коммит 43bc0d89db0f6f20cbc7e7e3d016ab07682e0d90). 

Пассажиры не были в первоначальных требованиях. Если требования изменились, дай знать, исправлю тогда.

**Comment by shinnik** [comment]
Изменились, да @alekseik1

**Comment by alekseik1** [comment]
Закрываю, т.к. проблема решена
