### ISSUE TITLE
Добавить метод, который отдает марки автомобилей из словаря

### ISSUE THREAD

**Issue by shinnik** [alekseik1/tt-ridesharing-backend#62]
http://tyresaddict.ru/help/databases/cars/
Вот отсюда можно тягать, например

GET /cars/models?search='Audi'

['Audi Q8', 'Audi R8', ...]

**Comment by alekseik1** [comment]
Сделано в ea1d8b2d25a3e4fcffbe7557ccb26df91a7aa616 и b229fbc0aa23423080cc00238a747249b28a80a8
