### ISSUE TITLE
Пофиксить баг с эластиком на мастере (срочняк)

### ISSUE THREAD

**Issue by shinnik** [alekseik1/tt-ridesharing-backend#65]
**Проблема:**
Периодически некоторые запросы на мастере отваливаются с ошибкой 403 (см. картинку). Хотелось бы, чтобы это прошло

**Ожидаемое поведение:**
Ошибок нет

![Screenshot from 2020-05-18 00-56-07](https://user-images.githubusercontent.com/38573075/82161066-73043180-98a2-11ea-9e63-f1a495b18c11.png)
![Screenshot from 2020-05-18 00-56-25](https://user-images.githubusercontent.com/38573075/82161067-739cc800-98a2-11ea-9aad-cf073ee232a7.png)

**Comment by shinnik** [comment]
Проблема не только по урлу /api/user. Наблюдались и по другим эндпоинтам тоже

**Comment by alekseik1** [comment]
После переезда на MCS проблемы ушли.

На heroku это было вызвано используемым сервисом bonsai: по-видимому, они хотели, чтобы на эластик ходили через сертификат, а я этого не сделал.
