### ISSUE TITLE
Реализовать поиск по неполному совпадению для организаций

### ISSUE THREAD

**Issue by shinnik** [alekseik1/tt-ridesharing-backend#66]
**Проблема:**
organization/search?query= ищет сейчас только по полному совпадению query и названия организации
**Желаемое поведение:**
Поиск выдает совпадения по части организаций.

**Программа максимум:**
Реализовать fuzzy matching для поиска организаций

**Comment by alekseik1** [comment]
Перенес поиск на elastic, лучше пока сделать не смогу
