### ISSUE TITLE
POST **/api/updateFirebaseRegistrationToken**

### ISSUE THREAD

**Issue by Kyzyl-ool** [alekseik1/tt-ridesharing-backend#70]
Эндпоинт для обновления токена в firebase Messaging.

Он кстати на фронте уже реализован.

**Comment by alekseik1** [comment]
@Kyzyl-ool тебе именно такой адрес эндпоинта нужен? В каком формате будете слать token?

**Comment by alekseik1** [comment]
Не очень нравится, как отправляется token в файле `lib/models/NotificationsModel.ts`

Хочу, чтобы приходил json вида
```json
{
  "firebase_token": "value"
}
```
Не совсем понял, отправляет ли фронт в таком формате или нет

**Comment by alekseik1** [comment]
Сделал в b81ca4be6a50481f74d425201e383087de7737bc

Эндпоинт из названия, формат -- как в комменте.

> Не очень нравится, как отправляется token в файле `lib/models/NotificationsModel.ts`
> 
> Хочу, чтобы приходил json вида
> 
> ```json
> {
>   "firebaseToken": "value"
> }
> ```
> 
> Не совсем понял, отправляет ли фронт в таком формате или нет

**Comment by alekseik1** [comment]
По логам увидел, что приходит json вида
```json
{
  "token": "value"
}
```
Подогнал под это в e7d8b5e22f2daaa2f5e789ceed05bbe883939a07

**Comment by alekseik1** [comment]
Готово на фронте и на беке, соединилось все. Закрываю
